backend:
  name: github
  repo: commit42/new-site-c42

media_folder: static/assets
public_folder: assets

publish_mode: editorial_workflow

logo_url: https://www.commit42.com/assets/favicon.png

site_url: https://www.commit42.com

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: blog
    label: Articles
    folder: src/pages/blog
    create: true
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - { name: title, label: Titre }
      - { name: date, label: Date, widget: date }
      - {
          name: author,
          label: Auteur,
          widget: relation,
          collection: authors,
          searchFields: ["name", "avatar"],
          valueField: name,
          multiple: true,
        }
      - { name: thumbnail, label: Vignette, widget: image }
      - {
          name: tags,
          label: Tags (séparer par une virgule et un espace),
          widget: list,
        }
      - { name: body, label: Texte, widget: markdown }

  - name: authors
    label: Auteurs
    identifier_field: name
    folder: src/pages/authors
    create: true
    fields:
      - { name: name, label: Nom, widget: string }
      - { name: avatar, label: Avatar, widget: image }
  - name: pages
    label: Pages
    files:
      - file: src/content/index.md
        label: Page d'accueil
        name: index
        fields:
          - {
              name: pageName,
              label: Nom de la page (en minuscules),
              widget: string,
            }
          - {
              name: head,
              label: En-tête,
              widget: object,
              fields:
                [
                  { name: image, label: Image, widget: image },
                  { name: heading, label: Titre, widget: string },
                  { name: description, label: Description, widget: text },
                ],
            }
          - {
              name: servicesList,
              label: Liste des services,
              widget: object,
              fields:
                [
                  { name: heading, label: Titre, widget: string },
                  {
                    name: services,
                    label: Services,
                    widget: list,
                    fields:
                      [
                        { name: title, label: Titre, widget: string },
                        { name: description, label: Description, widget: text },
                        {
                          name: icon,
                          label: Nom de l'icône associée,
                          widget: string,
                        },
                      ],
                  },
                ],
            }
          - {
              name: pitch,
              label: Pitch,
              widget: list,
              fields:
                [
                  { name: title, label: Titre, widget: string },
                  { name: description, label: Description, widget: text },
                  { name: image, label: Image, widget: image },
                  { name: darkBg, label: Fond noir ?, widget: boolean },
                ],
            }
          - {
              name: testimonialsList,
              label: Liste des temoignages,
              widget: object,
              fields:
                [
                  { name: heading, label: Titre, widget: string },
                  {
                    name: testimonials,
                    label: Témoignages,
                    widget: list,
                    fields:
                      [
                        { name: text, label: Texte, widget: text },
                        { name: author, label: Auteur, widget: string },
                        { name: rating, label: Note (sur 5), widget: number },
                      ],
                  },
                ],
            }
      - file: src/pages/content/blog.md
        label: Page blog
        name: Blog
        fields:
          - {
              name: pageName,
              label: Nom de la page (en minuscules),
              widget: string,
            }
          - { name: header, label: Titre, widget: string }
          - { name: description, label: Description, widget: text }
          - { name: image, label: Image, widget: image }
      - file: src/pages/content/societe.md
        label: Page societe
        name: Societe
        fields:
          - {
              name: pageName,
              label: Nom de la page (en minuscules),
              widget: string,
            }
          - {
              name: hero,
              label: Image(s) d'entête,
              widget: object,
              fields:
                [
                  { name: imgHeader, label: Image d'en-tête, widget: image },
                  {
                    name: imgHeaderAnim,
                    label: Autre img pour animation,
                    widget: image,
                  },
                ],
            }
          - {
              name: teamList,
              label: La dream team,
              widget: object,
              fields:
                [
                  { name: heading, label: Titre, widget: string },
                  {
                    name: members,
                    label: Membres de l'équipe,
                    widget: list,
                    fields:
                      [
                        { name: avatar, label: Avatar, widget: image },
                        { name: name, label: Nom et/ou prénom, widget: string },
                        { name: job, label: Métier, widget: string },
                        {
                          name: presentation,
                          label: Présentation,
                          widget: text,
                        },
                        {
                          name: socials,
                          label: Réseaux Sociaux,
                          widget: list,
                          fields:
                            [
                              { name: name, label: Nom, widget: string },
                              { name: link, label: Link, widget: string },
                            ],
                        },
                      ],
                  },
                ],
            }
          - {
              name: office,
              label: Locaux,
              widget: object,
              fields:
                [
                  { name: heading, label: Titre, widget: string },
                  { name: description, label: Description, widget: text },
                  {
                    name: pictures,
                    label: Photos,
                    widget: list,
                    fields: [{ name: picture, label: Photo, widget: image }],
                  },
                ],
            }
          - {
              name: contact,
              label: Contact,
              widget: object,
              fields:
                [
                  {
                    name: headerContact,
                    label: En-tête contact,
                    widget: object,
                    fields:
                      [
                        { name: imgHeader, label: Image, widget: image },
                        { name: heading, label: Titre, widget: string },
                      ],
                  },
                  {
                    name: contactForm,
                    label: Labels formulaire de contact,
                    widget: object,
                    fields:
                      [
                        {
                          name: name,
                          label: Nom,
                          widget: object,
                          fields:
                            [
                              { name: label, label: Label, widget: string },
                              {
                                name: placeholder,
                                label: Placeholder,
                                widget: string,
                              },
                            ],
                        },
                        {
                          name: surname,
                          label: Prénom,
                          widget: object,
                          fields:
                            [
                              { name: label, label: Label, widget: string },
                              {
                                name: placeholder,
                                label: Placeholder,
                                widget: string,
                              },
                            ],
                        },
                        {
                          name: email,
                          label: Email,
                          widget: object,
                          fields:
                            [
                              { name: label, label: Label, widget: string },
                              {
                                name: placeholder,
                                label: Placeholder,
                                widget: string,
                              },
                            ],
                        },
                        {
                          name: phoneNumber,
                          label: Numéro de téléphone,
                          widget: object,
                          fields:
                            [
                              { name: label, label: Label, widget: string },
                              {
                                name: placeholder,
                                label: Placeholder,
                                widget: string,
                              },
                            ],
                        },
                        {
                          name: subject,
                          label: Sujet,
                          widget: object,
                          fields:
                            [
                              { name: label, label: Label, widget: string },
                              {
                                name: placeholder,
                                label: Placeholder,
                                widget: string,
                              },
                            ],
                        },
                        {
                          name: textarea,
                          label: Partie texte,
                          widget: object,
                          fields:
                            [
                              { name: label, label: Label, widget: string },
                              {
                                name: placeholder,
                                label: Placeholder,
                                widget: string,
                              },
                            ],
                        },
                      ],
                  },
                  {
                    name: contactLinks,
                    label: Informations de contact,
                    widget: object,
                    fields:
                      [
                        { name: adress, label: Adresse, widget: string },
                        {
                          name: phoneNumber,
                          label: Numéro de téléphone,
                          widget: string,
                        },
                        { name: email, label: Email, widget: string },
                      ],
                  },
                ],
            }
          - {
              name: gpsDatas,
              label: Coordonnées GPS,
              widget: object,
              fields:
                [
                  { name: latitude, label: Latitude, widget: string },
                  { name: longitude, label: Longitude, widget: string },
                ],
            }
      - file: src/pages/content/pwa.md
        label: Page PWA
        name: PWA
        fields:
          - {
              name: pageName,
              label: Nom de la page (en minuscules),
              widget: string,
            }
          - {
              name: hero,
              label: hero,
              widget: object,
              fields:
                [
                  { name: image, label: Image, widget: image },
                  { name: heading, label: Titre, widget: string },
                  { name: text, label: Texte, widget: text },
                  { name: message, label: Info, widget: text },
                ],
            }
          - {
              name: characteristics,
              label: Caractéristiques,
              widget: list,
              fields:
                [
                  {
                    name: icon,
                    label: Icone (https://react.semantic-ui.com/elements/icon/),
                    widget: string,
                  },
                  { name: title, label: Titre, widget: string },
                  { name: description, label: Description, widget: string },
                  { name: bgColor, label: Bg primaire ?, widget: boolean },
                ],
            }
          - {
              name: schema,
              label: Schéma,
              widget: object,
              fields:
                [
                  { name: heading, label: Titre, widget: string },
                  { name: description, label: Description, widget: text },
                  { name: image, label: Image, widget, image },
                ],
            }
          - {
              name: examples,
              label: Exemples PWA,
              widget: object,
              fields:
                [
                  { name: heading, label: Titre, widget: string },
                  { name: description, label: Description, widget: string },
                  {
                    name: examplesList,
                    label: Liste d'exemples,
                    widget: list,
                    fields:
                      [
                        { name: icon, label: Icone, widget: string },
                        { name: title, label: Titre, widget: string },
                        {
                          name: bgColor,
                          label: Bg primaire ?,
                          widget: boolean,
                        },
                      ],
                  },
                ],
            }
          - {
              name: references,
              label: Références PWA,
              widget: object,
              fields:
                [
                  { name: heading, label: Titre, widget: string },
                  {
                    name: referencesList,
                    label: Liste des références,
                    widget: list,
                    fields:
                      [
                        { name: image, label: Image, widget: image },
                        { name: heading, label: Titre, widget: string },
                        { name: description, label: description, widget: text },
                      ],
                  },
                ],
            }
      - file: src/pages/content/ecommerce.md
        label: Page E-commerce
        name: ecommerce
        fields:
          - {
              name: pageName,
              label: Nom de la page (en minuscules),
              widget: string,
            }
          - {
              name: hero,
              label: En-tête,
              widget: object,
              fields:
                [
                  { name: heading, label: Titre, widget: string },
                  { name: text, label: Texte, widget: text },
                  { name: image, label: Image, widget: image },
                ],
            }
          - {
              name: references,
              label: Références,
              widget: object,
              fields:
                [
                  { name: title, label: Titre, widget: text },
                  {
                    name: referencesList,
                    label: Liste des références,
                    widget: list,
                    fields:
                      [
                        { name: title, label: Titre, widget: string },
                        { name: description, label: description, widget: text },
                        { name: image, label: Image, widget: image },
                      ],
                  },
                ],
            }
      - file: src/pages/content/footer.md
        label: Footer
        name: footer
        fields:
          - {
              name: pageName,
              label: Nom de la page (en minuscules),
              widget: string,
            }
          - { name: bottomText, label: Phrase en bas de page, widget: string }
          - {
              name: contacts,
              label: Contacts,
              widget: object,
              fields:
                [
                  { name: logo, label: Logo, widget: image },
                  {
                    name: contactsList,
                    label: Liste des contacts,
                    widget: list,
                    fields:
                      [
                        { name: icon, label: Icone, widget: string },
                        {
                          name: name,
                          label: Nom (adresse,
                          tel...),
                          widget: string,
                        },
                        { name: text, label: Text, widget: string },
                        { name: link, label: Lien, widget: string },
                      ],
                  },
                ],
            }
          - {
              name: pagesList,
              label: Liste des pages du site,
              widget: list,
              fields: [{ name: name, label: Nom, widget: string }],
            }
          - {
              name: socialsList,
              label: Liste des réseaux sociaux,
              widget: list,
              fields:
                [
                  { name: name, label: Nom, widget: string },
                  { name: link, label: Lien, widget: string },
                ],
            }
      - file: src/pages/content/navbar.md
        label: Navbar
        name: navbar
        fields:
          - {
              name: pageName,
              label: Nom de la page (en minuscules),
              widget: string,
            }
          - { name: image, label: Logo, widget: image }
          - {
              name: pageList,
              label: Pages,
              widget: list,
              allow_add: true,
              fields:
                [
                  { name: name, label: Nom, widget: string },
                  { name: icon, label: Icone, widget: string },
                ],
            }
