backend:
  name: github
  repo: commit42/new-site-c42

media_folder: static/assets
public_folder: assets

publish_mode: editorial_workflow

logo_url: https://www.commit42.com/assets/favicon.png

site_url: https://www.commit42.com

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: blog
    label: Articles
    folder: src/pages/blog
    create: true
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - { name: title, label: Titre }
      - { name: date, label: Date, widget: date }
      - { name: author, label: Auteur }
      - { name: thumbnail, label: Vignette, widget: image }
      - {
          name: tags,
          label: Tags (séparer par une virgule et un espace),
          widget: list,
        }
      - { name: body, label: Texte, widget: markdown }

  - name: pages
    label: Pages
    files:
      - file: src/pages/content/index.md
        label: Page d'accueil
        name: index
        fields:
          - {
              name: pageName,
              label: Nom de la page (en minuscules),
              widget: string,
            }
          - {
              name: head,
              label: En-tête,
              widget: object,
              fields:
                [
                  { name: image, label: Image, widget: image },
                  { name: heading, label: Titre, widget: string },
                  { name: description, label: Description, widget: text },
                ],
            }
          - {
              name: services,
              label: Liste des services,
              widget: object,
              fields:
                [
                  { name: heading, label: Titre, widget: string },
                  {
                    name: servicesList,
                    label: Services,
                    widget: list,
                    fields:
                      [
                        { name: title, label: Titre, widget: string },
                        { name: description, label: Description, widget: text },
                        {
                          name: icon,
                          label: Nom de l'icône associée,
                          widget: string,
                        },
                      ],
                  },
                ],
            }
          - {
              name: pitch,
              label: Pitch,
              widget: list,
              fields:
                [
                  { name: title, label: Titre, widget: string },
                  { name: description, label: Description, widget: text },
                  { name: image, label: Image, widget: image },
                  { name: darkBg, label: Fond noir ?, widget: boolean },
                ],
            }
          - {
              name: testimonials,
              label: Liste des temoignages,
              widget: object,
              fields:
                [
                  { name: heading, label: Titre, widget: string },
                  {
                    name: testimonialsList,
                    label: Témoignages,
                    widget: list,
                    fields:
                      [
                        { name: text, label: Texte, widget: text },
                        { name: author, label: Auteur, widget: string },
                        { name: rating, label: Note (sur 5), widget: number },
                      ],
                  },
                ],
            }
      - file: src/pages/content/blog.md
        label: Page blog
        name: Blog
        fields:
          - {
              name: pageName,
              label: Nom de la page (en minuscules),
              widget: string,
            }
          - { name: header, label: Titre, widget: string }
          - { name: description, label: Description, widget: text }
          - { name: image, label: Image, widget: image }
      - file: src/pages/content/societe.md
        label: Page societe
        name: Societe
        fields:
          - {
              name: pageName,
              label: Nom de la page (en minuscules),
              widget: string,
            }
          - { name: header, label: Image d'en-tête, widget: image }
          - {
              name: teamList,
              label: La dream team,
              widget: object,
              fields:
                [
                  { name: heading, label: Titre, widget: string },
                  {
                    name: members,
                    label: Membres de l'équipe,
                    widget: list,
                    fields:
                      [
                        { name: avatar, label: Avatar, widget: image },
                        { name: name, label: Nom et/ou prénom, widget: string },
                        {
                          name: presentation,
                          label: Présentation,
                          widget: text,
                        },
                        {
                          name: socials,
                          label: Réseaux Sociaux,
                          widget: list,
                          fields:
                            [
                              { name: name, label: Nom, widget: string },
                              { name: link, label: Link, widget: string },
                            ],
                        },
                      ],
                  },
                ],
            }
          - {
              name: office,
              label: Locaux,
              widget: object,
              fields:
                [
                  { name: heading, label: Titre, widget: string },
                  { name: description, label: Description, widget: text },
                  {
                    name: pictures,
                    label: Photos,
                    widget: list,
                    fields: [{ name: picture, label: Photo, widget: image }],
                  },
                ],
            }
          - {
              name: contact,
              label: Contact,
              widget: object,
              fields:
                [
                  {
                    name: headerContact,
                    label: En-tête contact,
                    widget: object,
                    fields:
                      [
                        { name: imgHeader, label: Image, widget: image },
                        { name: heading, label: Titre, widget: string },
                      ],
                  },
                  {
                    name: contactForm,
                    label: Labels formulaire de contact,
                    widget: object,
                    fields:
                      [
                        {
                          name: name,
                          label: Nom,
                          widget: object,
                          fields:
                            [
                              { name: label, label: Label, widget: string },
                              {
                                name: placeholder,
                                label: Placeholder,
                                widget: string,
                              },
                            ],
                        },
                        {
                          name: surname,
                          label: Prénom,
                          widget: object,
                          fields:
                            [
                              { name: label, label: Label, widget: string },
                              {
                                name: placeholder,
                                label: Placeholder,
                                widget: string,
                              },
                            ],
                        },
                        {
                          name: email,
                          label: Email,
                          widget: object,
                          fields:
                            [
                              { name: label, label: Label, widget: string },
                              {
                                name: placeholder,
                                label: Placeholder,
                                widget: string,
                              },
                            ],
                        },
                        {
                          name: phoneNumber,
                          label: Numéro de téléphone,
                          widget: object,
                          fields:
                            [
                              { name: label, label: Label, widget: string },
                              {
                                name: placeholder,
                                label: Placeholder,
                                widget: string,
                              },
                            ],
                        },
                        {
                          name: subject,
                          label: Sujet,
                          widget: object,
                          fields:
                            [
                              { name: label, label: Label, widget: string },
                              {
                                name: placeholder,
                                label: Placeholder,
                                widget: string,
                              },
                            ],
                        },
                        {
                          name: textarea,
                          label: Partie texte,
                          widget: object,
                          fields:
                            [
                              { name: label, label: Label, widget: string },
                              {
                                name: placeholder,
                                label: Placeholder,
                                widget: string,
                              },
                            ],
                        },
                      ],
                  },
                  {
                    name: contactLinks,
                    label: Informations de contact,
                    widget: object,
                    fields:
                      [
                        { name: adress, label: Adresse, widget: string },
                        {
                          name: phoneNumber,
                          label: Numéro de téléphone,
                          widget: string,
                        },
                        { name: email, label: Email, widget: string },
                      ],
                  },
                ],
            }
          - {
              name: gpsDatas,
              label: Coordonnées GPS,
              widget: object,
              fields:
                [
                  { name: latitude, label: Latitude, widget: string },
                  { name: longitude, label: Longitude, widget: string },
                ],
            }
