backend:
  name: github
  repo: commit42/new-site-c42

media_folder: static/assets
public_folder: assets

publish_mode: editorial_workflow

logo_url: https://www.commit42.com/assets/logo.png

site_url: https://www.commit42.com

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: blog
    label: Post
    folder: src/pages/blog
    create: true
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - { name: author, label: Author }
      - { name: thumbnail, label: Thumbnail, widget: image }
      - {
          name: tags,
          label: Tags (séparer par une virgule et un espace),
          widget: list,
        }
      - { name: body, label: Body, widget: markdown }

  - name: pages
    label: Page
    files:
      - file: src/pages/content/index.md
        label: Landing Page
        name: index
        fields:
          - {
              name: header,
              label: Header,
              widget: object,
              fields:
                [
                  { name: heading, label: Heading, widget: string },
                  { name: description, label: Description, widget: text },
                  { name: image, label: Image, widget: image },
                ],
            }
          - { name: description, label: Description, widget: text }
      - file: src/pages/content/blog.md
        label: Blog Page
        name: Blog
        fields:
          - { name: header, label: Header, widget: string }
          - { name: description, label: Description, widget: text }
