backend:
  name: github
  repo: commit42/new-site-c42

media_folder: static/assets
public_folder: assets

publish_mode: editorial_workflow

logo_url: https://www.commit42.com/assets/favicon.png

site_url: https://www.commit42.com

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "-"

collections:
  - name: blog
    label: Articles
    folder: src/pages/blog
    create: true
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - { name: title, label: Titre }
      - { name: date, label: Date, widget: date }
      - { name: author, label: Auteur }
      - { name: thumbnail, label: Vignette, widget: image }
      - {
          name: tags,
          label: Tags (séparer par une virgule et un espace),
          widget: list,
        }
      - { name: body, label: Texte, widget: markdown }

  - name: pages
    label: Page
    files:
      - file: src/pages/content/index.md
        label: Page d'accueil
        name: index
        fields:
          - {
              name: pageName,
              label: Nom de la page (en minuscules),
              widget: string,
            }
          - {
              name: head,
              label: En-tête,
              widget: object,
              fields:
                [
                  { name: image, label: Image, widget: image },
                  { name: heading, label: Titre, widget: string },
                  { name: description, label: Description, widget: text },
                ],
            }
          - {
              name: servicesList,
              label: Liste des services,
              widget: object,
              fields:
                [
                  { name: heading, label: Titre, widget: string },
                  {
                    name: services,
                    label: Services,
                    widget: list,
                    fields:
                      [
                        { name: title, label: Titre, widget: string },
                        { name: description, label: Description, widget: text },
                        {
                          name: icon,
                          label: Nom de l'icône associée,
                          widget: string,
                        },
                      ],
                  },
                ],
            }
          - {
              name: pitch,
              label: Pitch,
              widget: list,
              fields:
                [
                  { name: title, label: Titre, widget: string },
                  { name: description, label: Description, widget: text },
                  { name: image, label: Image, widget: image },
                  { name: darkBg, label: Fond noir ?, widget: boolean },
                ],
            }
          - {
              name: testimonialsList,
              label: Liste des temoignages,
              widget: object,
              fields:
                [
                  { name: heading, label: Titre, widget: string },
                  {
                    name: testimonials,
                    label: Témoignages,
                    widget: list,
                    fields:
                      [
                        { name: text, label: Texte, widget: text },
                        { name: author, label: Auteur, widget: string },
                        { name: rating, label: Note (sur 5), widget: number },
                      ],
                  },
                ],
            }
      - file: src/pages/content/blog.md
        label: Page blog
        name: Blog
        fields:
          - {
              name: pageName,
              label: Nom de la page (en minuscules),
              widget: string,
            }
          - { name: header, label: Titre, widget: string }
          - { name: description, label: Description, widget: text }
          - { name: image, label: Image, widget: image }
